on: [pull_request]
jobs:
  SpellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: check-spelling/check-spelling@main
        with:
          experimental_apply_changes_via_bot: 0
          post_comment: ""
